# Generated by Django 4.2 on 2026-03-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Guruh nomi')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_groups', to=settings.AUTH_USER_MODEL, verbose_name='Tyutor')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='F.I.SH')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='TG Username')),
                ('tg_first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='TG Ismi')),
                ('tg_last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='TG Familiyasi')),
                ('tg_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dastur tili')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='parents_profiles/', verbose_name='Profil rasmi')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name="Qora ro'yxatdami?")),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Talaba ID (Login)')),
                ('password', models.CharField(max_length=128, verbose_name='Parol')),
                ('full_name', models.CharField(max_length=150, verbose_name="F.I.SH (O'qishdagi)")),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='TG Username')),
                ('tg_first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='TG Ismi')),
                ('tg_last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='TG Familiyasi')),
                ('tg_language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dastur tili')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='students_profiles/', verbose_name='Profil rasmi')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group', verbose_name='Guruhi')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='StudentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name="O'quv yili (Masalan: 2023-2024)")),
                ('course_level', models.PositiveSmallIntegerField(default=1, verbose_name='Kursi (1, 2, 3, 4)')),
                ('is_grant', models.BooleanField(default=False, verbose_name='Grant asosidami?')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shu yilgi kontrakt summasi')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Shu yil uchun to'langan summa")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Talaba kontrakti',
                'verbose_name_plural': 'Talabalar kontraktlari',
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="To'lov summasi")),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name="To'lov sanasi")),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.studentcontract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
        migrations.CreateModel(
            name='NotificationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_type_filter', models.CharField(choices=[('contract_only', "Faqat kontrakt asosida o'qiydiganlarga"), ('grant_only', "Faqat grant asosida o'qiydiganlarga"), ('all', 'Barchaga (Grant + Kontrakt)')], default='contract_only', max_length=20, verbose_name='Kimlarga (Grant/Kontrakt)')),
                ('target_debt_tier', models.PositiveSmallIntegerField(choices=[(0, "Qarzdan qat'i nazar (E'lonlar uchun)"), (25, "25% (1-chorak) to'lamaganlar uchun"), (50, "50% (Yarim yillik) to'lamaganlar uchun"), (75, "75% (3-chorak) to'lamaganlar uchun"), (100, "100% (To'liq) to'lamaganlar uchun")], verbose_name='Qarz chegarasi (Filtr)')),
                ('recipients', models.CharField(choices=[('student_only', "Faqat talabalarning o'ziga"), ('student_and_parent', 'Talaba va ularning Ota-onalariga'), ('parent_only', 'Faqat Ota-onalarga')], default='student_only', max_length=30, verbose_name='Kimlarga yuborilsin?')),
                ('message_text', models.TextField(verbose_name='Yuboriladigan xabar matni')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('send_time', models.TimeField(verbose_name='Kunlik yuborish vaqti')),
                ('groups', models.ManyToManyField(related_name='campaigns', to='users.group', verbose_name='Qaysi guruhlarga?')),
            ],
            options={
                'verbose_name': 'Xabarnoma',
                'verbose_name_plural': 'Xabarnomalar',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('father', 'Ota'), ('mother', 'Ona'), ('other', 'Boshqa (Aka/Opa)')], max_length=150, null=True, verbose_name='Qarindoshlik darajasi')),
                ('custom_role_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kimligi (Boshqa)')),
                ('status', models.CharField(choices=[('pending_otp', 'OTP kutilmoqda'), ('pending_admin', 'Admin tasdiqlashi kutilmoqda'), ('verified', 'Tasdiqlangan'), ('rejected', "Rad etilgan (Qora ro'yxat)")], default='pending_otp', max_length=20, verbose_name='Status')),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP Kod')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='OTP muddati')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.parent', verbose_name='Ota-ona')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='users.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Talaba va Ota-ona bog'lanishi",
                'verbose_name_plural': 'Talaba va Ota-onalar',
                'unique_together': {('student', 'parent')},
            },
        ),
    ]
