# Generated by Django 4.2 on 2026-03-17 08:25

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.AddField(
            model_name='studentcontract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan vaqti'),
        ),
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default=users.models.current_academic_year, max_length=9, verbose_name="O'quv yili")),
                ('file', models.FileField(upload_to='excel_imports/', verbose_name='Excel faylni yuklang')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan vaqti')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.group', verbose_name='Guruhni tanlang')),
            ],
            options={
                'verbose_name': 'Hisobot (Excel) kiritish',
                'verbose_name_plural': 'Hisobotlar (Excel) kiritish',
            },
        ),
    ]
