# Generated by Django 4.2 on 2026-04-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_created_at_studentcontract_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentparent',
            name='status',
            field=models.CharField(choices=[('pending_otp', 'OTP kutilmoqda'), ('pending_admin', 'Admin tasdiqlagan'), ('verified', 'Tasdiqlangan'), ('rejected', "Rad etilgan (Qora ro'yxat)")], default='pending_otp', max_length=20, verbose_name='Status'),
        ),
    ]
